// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/shortener_service_contract.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockshortenerService is a mock of shortenerService interface.
type MockshortenerService struct {
	ctrl     *gomock.Controller
	recorder *MockshortenerServiceMockRecorder
}

// MockshortenerServiceMockRecorder is the mock recorder for MockshortenerService.
type MockshortenerServiceMockRecorder struct {
	mock *MockshortenerService
}

// NewMockshortenerService creates a new mock instance.
func NewMockshortenerService(ctrl *gomock.Controller) *MockshortenerService {
	mock := &MockshortenerService{ctrl: ctrl}
	mock.recorder = &MockshortenerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockshortenerService) EXPECT() *MockshortenerServiceMockRecorder {
	return m.recorder
}

// AddOrigin mocks base method.
func (m *MockshortenerService) AddOrigin(ctx context.Context, originUrl string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOrigin", ctx, originUrl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddOrigin indicates an expected call of AddOrigin.
func (mr *MockshortenerServiceMockRecorder) AddOrigin(ctx, originUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOrigin", reflect.TypeOf((*MockshortenerService)(nil).AddOrigin), ctx, originUrl)
}

// GetOrigin mocks base method.
func (m *MockshortenerService) GetOrigin(ctx context.Context, shortUrl string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrigin", ctx, shortUrl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrigin indicates an expected call of GetOrigin.
func (mr *MockshortenerServiceMockRecorder) GetOrigin(ctx, shortUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrigin", reflect.TypeOf((*MockshortenerService)(nil).GetOrigin), ctx, shortUrl)
}
